spring.datasource.url=jdbc:postgresql://localhost:5432/severstal
spring.datasource.username=postgres
spring.datasource.password=Dima228*
spring.datasource.driver-class-name=org.postgresql.Driver





spring.flyway.enabled=true
spring.flyway.locations=classpath:db

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=static/**,public/**,templates/**
spring.devtools.restart.additional-paths=src/main/java
spring.thymeleaf.cache=false