CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    kind VARCHAR(255)
);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL
);


CREATE TABLE supplier_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES suppliers(id),
    product_id BIGINT REFERENCES products(id),
    price_per_kg DECIMAL(19, 2),
    date_from DATE,
    date_to DATE
);

CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES suppliers(id),
    delivery_date DATE
);

CREATE TABLE delivery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT REFERENCES deliveries(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    weight_kg DECIMAL(19, 2),
    price_per_kg DECIMAL(19, 2)
);